app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(r'^musics/$', views.MusicList.as_view(), name='music-list'),
    # path('', views.MusicList.as_view(), name='music_list'),
    path('view/<int:pk>', views.MusicView.as_view(), name='music_view'),
    path('new', views.MusicCreate.as_view(), name='music_new'),
    path('view/<int:pk>', views.MusicView.as_view(), name='music_view'),
    path('edit/<int:pk>', views.MusicUpdate.as_view(), name='music_edit'),
    path('delete/<int:pk>', views.MusicDelete.as_view(), name='music_delete'),

]

books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new', views.book_create, name='book_new'),
  path('edit/<int:pk>', views.book_update, name='book_edit'),
  path('delete/<int:pk>', views.book_delete, name='book_delete'),
]

ifcapi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('app.urls')),
]

ifcarros/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url,include
from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls', namespace='books')),
    url(r'^', include('app.urls')),
    path('', views.home),
]

app/models.py
from django.db import models

class Music(models.Model):
    
    class Meta:

        db_table = 'music'
    title = models.CharField(max_length=200)
    seconds = models.IntegerField()

    def __str__(self):
        return self.title

books/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books:book_edit', kwargs={'pk': self.pk})

books_cbv/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

theme/models.py
from django.db import models

# Create your models here.

app/musics/views.py
from rest_framework import generics
from .models import Music
from .serializers import MusicSerializer
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.forms import ModelForm


# Create your views here.
# class MusicList(generics.ListCreateAPIView):
#     model = Music
#     # template_name = ".html"
#     queryset = Music.objects.all()
#     serializer_class = MusicSerializer

# class MusicView(DetailView):
#     model = Music
    
# class MusicCreate(CreateView):
#     model = Music
#     fields = ['title', 'seconds']
#     success_url = reverse_lazy('music_list')

# class MusicUpdate(UpdateView):
#     model = Music
#     fields = ['title', 'seconds']
#     success_url = reverse_lazy('music_list')

# class MusicDelete(DeleteView):
#     model = Music
#     success_url = reverse_lazy('music_list')

class MusicForm(ModelForm):
    class Meta:
        model = Music
        fields = ['title', 'seconds']

def music_list(request, template_name='musics/music_list.html'):
    music = Music.objects.all()
    data = {}
    data['object_list'] = music
    return render(request, template_name, data)

def music_view(request, pk, template_name='musics/music_detail.html'):
    music= get_object_or_404(Music, pk=pk)    
    return render(request, template_name, {'object':music})

def music_create(request, template_name='musics/music_form.html'):
    form = MusicForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('music_list')
    return render(request, template_name, {'form':form})

def music_update(request, pk, template_name='musics/music_form.html'):
    music= get_object_or_404(Music, pk=pk)
    form = MusicForm(request.POST or None, instance=music)
    if form.is_valid():
        form.save()
        return redirect('music_list')
    return render(request, template_name, {'form':form})

def music_delete(request, pk, template_name='musics/music_confirm_delete.html'):
    music= get_object_or_404(Music, pk=pk)    
    if request.method=='POST':
        music.delete()
        return redirect('music_list')
    return render(request, template_name, {'object':music})

app/views.py
from rest_framework import generics
from .models import Music
from .serializers import MusicSerializer
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.forms import ModelForm


# Create your views here.
class MusicList(generics.ListCreateAPIView):
    model = Music
    # template_name = ".html"
    queryset = Music.objects.all()
    serializer_class = MusicSerializer

class MusicView(DetailView):
    model = Music
    
class MusicCreate(CreateView):
    model = Music
    fields = ['title', 'seconds']
    success_url = reverse_lazy('music_list')

class MusicUpdate(UpdateView):
    model = Music
    fields = ['title', 'seconds']
    success_url = reverse_lazy('music_list')

class MusicDelete(DeleteView):
    model = Music
    success_url = reverse_lazy('music_list')

books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.forms import ModelForm

from books.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

def book_list(request, template_name='books/book_list.html'):
    book = Book.objects.all()
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

def book_create(request, template_name='books/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books:book_list')
    return render(request, template_name, {'form':form})

def book_update(request, pk, template_name='books/book_form.html'):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books:book_list')
    return render(request, template_name, {'form':form})

def book_delete(request, pk, template_name='books/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)    
    if request.method=='POST':
        book.delete()
        return redirect('books:book_list')
    return render(request, template_name, {'object':book})

# class BookList(ListView):
#     model = Book

# class BookCreate(CreateView):
#     model = Book
#     fields = ['name', 'pages']
#     success_url = reverse_lazy('books:book_list')

# class BookUpdate(UpdateView):
#     model = Book
#     fields = ['name', 'pages']
#     success_url = reverse_lazy('books:book_list')

# class BookDelete(DeleteView):
#     model = Book
#     success_url = reverse_lazy('books:book_list')

theme/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

app/templates/musics/music_list.html
<h1>Books</h1>

<table border="1">
<thead>
    <tr>
    <th>Name</th>
    <th>Pages</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
</tbody>
</table>

<a href="{% url "music_new" %}">New</a>

books/templates/books/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books:book_list' %}">Books CBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

books/templates/books/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books:book_list' %}">Books CBV</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

books/templates/books/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books:book_list' %}">Books CBV</a></h2>

<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books:book_edit' book.id %}">edit</a>
    <a href="{% url 'books:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books:book_new' %}">New</a>

{% endblock %}

books_cbv/templates/books_cbv/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

books_cbv/templates/books_cbv/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

theme/templates/base.html
{% load static %}

<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="header">
        <h1><a href="/">Django CRUD Example</a></h1>
    </div><!-- header -->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- content -->
</body>
</html>

theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'books:book_list' %}">Class Based Views</a><br>
{% endblock %}